name: CI - Build Backend

on:
  pull_request:
    branches: [ master ]

env:
  POSTGRESQL_VERSION: 13.1
  POSTGRESQL_DB: cosmetic-ingredient-checker
  POSTGRESQL_USER: hungpd170501
  POSTGRESQL_PASSWORD: password
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: ${{ env.POSTGRESQL_DB }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_USER }}
          POSTGRES_DB: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Build and run Unit/Integration Tests with Maven
        run: mvn -ntp -B verify